name: Update playlist

on:
  schedule:
    - cron: "15 2 * * *"   # har kuni 02:15 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build playlist
        run: python3 build.py
      - name: Commit and push
        run: |
          git config user.name "playlist-bot"
          git config user.email "playlist-bot@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist" || exit 0
          git push
